spring:
  activemq:
    broker-url: tcp://192.168.0.226:61616
    user: admin
    password: bjyappam
# 开启 JMS pool,  添加 activemq-pool 的支持
    pool:
      enabled: true
      max-connections: 50
          
server:
  port: 8088          